[package]
name = "rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[[bin]]
name = "2022_day1"
path = "src/2022_day1.rs"


[[bin]]
name = "2022_day2"
path = "src/2022_day2.rs"